name: Flutter iOS Build

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: macos-latest  # macOS runner for iOS build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clones your repo

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Use the stable Flutter version

    - name: Install dependencies
      run: flutter pub get  # Get dependencies

    - name: Set up iOS dependencies
      run: sudo gem install cocoapods  # Install CocoaPods if needed

    - name: Build iOS app
      run: flutter build ios --release  # Build the iOS app for release

    - name: Create iOS Artifact
      run: |
        cd build/ios/iphoneos
        zip -r FlutterApp.zip Runner.app  # Create a .zip of the iOS app

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FlutterApp.zip
        path: build/ios/iphoneos/FlutterApp.zip  # Upload the iOS build artifact
